### ISSUE TITLE
Login Link 

### ISSUE THREAD

**Issue by xcvy** [ns-dokuzentrum-muenchen/departure-neuaubing-frontend#148]
Minor question: is Gmail the links do automatically clickable. Is this a google security feature or can we solve this by styling the link as a link in the email?

<img width="810" alt="Bildschirmfoto 2022-07-30 um 12 26 32" src="https://user-images.githubusercontent.com/82038622/181906242-987c9d84-1c18-4125-b903-402060a243b1.png">

vs 

<img width="580" alt="Bildschirmfoto 2022-07-30 um 11 13 17" src="https://user-images.githubusercontent.com/82038622/181906249-0bea3a5f-dd31-4e0c-8676-07b1f85287e0.png">
?

**Comment by n-kort** [comment]
The link was actually broken, due to a missing placeholder in the translation 🙃. Fixed it now
