### ISSUE TITLE
Mothballing Sprachanalyse-Werkzeugs

### ISSUE THREAD

**Issue by xcvy** [ns-dokuzentrum-muenchen/departure-neuaubing-frontend#149]
Hi Nic,
after 2 years the NS-Doku team are no longer taking submissions for the “Sprachanalyse-Werkzeugs”. Could you take the submit box offline for Franz Wagners page? Or is this something I could do in the backend?

Thanks

https://departure-neuaubing.nsdoku.de/projekte/mind-the-memory-gap#begriff=/begriffe/einsatz

![pastedImage](https://github.com/ns-dokuzentrum-muenchen/departure-neuaubing-frontend/assets/82038622/1e41a0cb-fcac-456a-ba0a-e2343be5a20b)

**Comment by n-kort** [comment]
@xcvy just checked this and I think the simplest way is to disable comments in WP for those specific posts.

**Comment by xcvy** [comment]
Amazing thanks for looking. I will go through it.

**Comment by xcvy** [comment]
Ah, problem: Disabling comments hides all comments. I think we are looking for no new comments…

**Comment by n-kort** [comment]
ah. yes not optimal. I'll change that!

**Comment by n-kort** [comment]
@xcvy actually this also applies to the 'Bietrag einreichen' thing right?

**Comment by xcvy** [comment]
Yes, but only in the Begriffe / Sprachanalyse-Werkzeugs. I don't think for the image submissions.

**Comment by n-kort** [comment]
OK, should be done
